name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.2.2
      with:
        arguments: jacocoTestReport
        
    - name: Add Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 90
        min-coverage-changed-files: 90
        title: Jacoco coverage information
        
    - name: Jacoco Code Coverage Report
      id: jacoco_reporter
      uses: PavanMudigonda/jacoco-reporter@v4.5
      with:
        coverage_results_path: build/reports/jacoco/test/jacocoTestReport.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 90
        fail_below_threshold: true
        skip_check_run: false
        publish_only_summary: false
        
    - name: Upload Jacoco Code Coverage Artifacts
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: code-coverage-report-html
        path: build/reports/jacoco/test/html/
